<?php

namespace Omnify\Core\Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Omnify\Core\Models\User;
use Omnify\Core\CoreServiceProvider;
use Orchestra\Testbench\TestCase as OrchestraTestCase;

/**
 * Base TestCase
 *
 * テストの基底クラス
 * Uses the package's User model directly (not Fixture) to work with enforceMorphMap.
 */
abstract class TestCase extends OrchestraTestCase
{
    use RefreshDatabase;

    protected function getPackageProviders($app): array
    {
        return [
            CoreServiceProvider::class,
            \Laravel\Sanctum\SanctumServiceProvider::class,
            \Inertia\ServiceProvider::class,
        ];
    }

    protected function defineEnvironment($app): void
    {
        // Application key (required for web middleware session/cookie encryption)
        $app['config']->set('app.key', 'base64:'.base64_encode(str_repeat('x', 32)));

        // SSO Client設定
        $app['config']->set('omnify-auth.console.url', 'https://test.console.omnify.jp');
        $app['config']->set('omnify-auth.service.slug', 'test-service');
        $app['config']->set('omnify-auth.service.secret', 'test-secret');
        $app['config']->set('omnify-auth.user_model', User::class);

        // Admin routes middleware - simplified for testing
        // テスト環境ではadmin routesのmiddlewareを簡略化
        $app['config']->set('omnify-auth.routes.admin_middleware', ['api']);

        // Access (IAM) routes middleware - simplified for testing
        $app['config']->set('omnify-auth.routes.access_middleware', ['web']);

        // Register fixture views for Inertia testing (provides app.blade.php)
        $app['config']->set('view.paths', [__DIR__.'/Fixtures/views']);

        // Disable Inertia page component file existence check (components are not compiled in tests)
        $app['config']->set('inertia.testing.ensure_pages_exist', false);

        // データベース設定
        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);

        // 認証設定
        $app['config']->set('auth.defaults.guard', 'web');
        $app['config']->set('auth.guards.web', [
            'driver' => 'session',
            'provider' => 'users',
        ]);
        $app['config']->set('auth.providers.users', [
            'driver' => 'eloquent',
            'model' => User::class,
        ]);

        // Sanctum設定
        $app['config']->set('sanctum.stateful', ['localhost', '127.0.0.1']);
    }

    protected function defineDatabaseMigrations(): void
    {
        // Load package migrations (generated by Omnify)
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations/omnify');

        // Load custom/override migrations (run after omnify-generated ones)
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');

        // Load test fixture migrations (e.g., Sanctum personal_access_tokens)
        $this->loadMigrationsFrom(__DIR__.'/Fixtures/database/migrations');
    }

    /**
     * テスト用ユーザーを作成
     */
    protected function createUser(array $attributes = []): User
    {
        return User::factory()->create($attributes);
    }
}
