<?php

namespace Omnify\Core\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class BrandResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'console_brand_id' => $this->console_brand_id,
            'console_organization_id' => $this->console_organization_id,
            'slug' => $this->slug,
            'name' => $this->name,
            'description' => $this->description,
            'logo_url' => $this->logo_url,
            'cover_image_url' => $this->cover_image_url,
            'website' => $this->website,
            'is_active' => $this->is_active,
            'is_standalone' => $this->is_standalone,
            'settings' => $this->settings,
            'metadata' => $this->metadata,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'deleted_at' => $this->deleted_at?->toISOString(),
        ];
    }
}
