<?php

namespace Omnify\Core\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class TeamPermissionResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'console_organization_id' => $this->console_organization_id,
            'console_team_id' => $this->console_team_id,
            'permission_id' => $this->permission_id,
            'permission' => $this->whenLoaded('permission', fn() => new \Omnify\Core\Http\Resources\PermissionResource($this->permission)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'deleted_at' => $this->deleted_at?->toISOString(),
        ];
    }
}
