<?php

namespace Omnify\Core\Http\Resources\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class UserResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'email_verified_at' => $this->email_verified_at?->toISOString(),
            'is_default_password' => $this->is_default_password,
            'is_active' => $this->is_active,
            'date_of_birth' => $this->date_of_birth?->toDateString(),
            'phone' => $this->phone,
            'address' => $this->address,
            'bank' => $this->bank,
            'avatar_url' => $this->avatar_url,
            'bio' => $this->bio,
            'is_standalone' => $this->is_standalone,
            'console_user_id' => $this->console_user_id,
            'console_organization_id' => $this->console_organization_id,
            'console_access_token' => $this->console_access_token,
            'console_refresh_token' => $this->console_refresh_token,
            'console_token_expires_at' => $this->console_token_expires_at?->toISOString(),
            'two_factor_confirmed_at' => $this->two_factor_confirmed_at?->toISOString(),
            'roles' => $this->whenLoaded('roles', fn() => \Omnify\Core\Http\Resources\RoleResource::collection($this->roles)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'deleted_at' => $this->deleted_at?->toISOString(),
        ];
    }
}
