<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\BranchLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * BranchBaseModel
 *
 * @property string $console_branch_id
 * @property string $console_organization_id
 * @property string|null $code
 * @property string $slug
 * @property string $name
 * @property bool $is_headquarters
 * @property bool $is_active
 * @property string|null $console_brand_id
 * @property bool $is_standalone
 * @property string|null $address
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $timezone
 * @property string|null $currency
 * @property string|null $locale
 * @property array|null $settings
 * @property array|null $metadata
 */
class BranchBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'branches';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = BranchLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = BranchLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'console_branch_id',
        'console_organization_id',
        'code',
        'slug',
        'name',
        'is_headquarters',
        'is_active',
        'console_brand_id',
        'is_standalone',
        'address',
        'phone',
        'email',
        'timezone',
        'currency',
        'locale',
        'settings',
        'metadata',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'is_headquarters' => 'boolean',
            'is_active' => 'boolean',
            'is_standalone' => 'boolean',
            'settings' => 'array',
            'metadata' => 'array',
        ];
    }

}
