<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\LocationLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * LocationBaseModel
 *
 * @property string $console_location_id
 * @property string $console_branch_id
 * @property string $console_organization_id
 * @property string $code
 * @property string $name
 * @property string $type
 * @property bool $is_active
 * @property bool $is_standalone
 * @property string|null $address
 * @property string|null $city
 * @property string|null $state_province
 * @property string|null $postal_code
 * @property string|null $country_code
 * @property float|null $latitude
 * @property float|null $longitude
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $timezone
 * @property int|null $capacity
 * @property int $sort_order
 * @property string|null $description
 * @property array|null $settings
 * @property array|null $metadata
 */
class LocationBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'locations';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = LocationLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = LocationLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'console_location_id',
        'console_branch_id',
        'console_organization_id',
        'code',
        'name',
        'type',
        'is_active',
        'is_standalone',
        'address',
        'city',
        'state_province',
        'postal_code',
        'country_code',
        'latitude',
        'longitude',
        'phone',
        'email',
        'timezone',
        'capacity',
        'sort_order',
        'description',
        'settings',
        'metadata',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'is_standalone' => 'boolean',
            'latitude' => 'decimal:7',
            'longitude' => 'decimal:7',
            'capacity' => 'integer',
            'sort_order' => 'integer',
            'settings' => 'array',
            'metadata' => 'array',
        ];
    }

}
