<?php

namespace Omnify\SsoClient\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\SsoClient\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\SsoClient\Models\Base\Locales\PasswordResetTokenLocales;

/**
 * PasswordResetTokenBaseModel
 *
 * @property string $email
 * @property string $token
 * @property mixed|null $created_at
 */
class PasswordResetTokenBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    /**
     * The table associated with the model.
     */
    protected $table = 'password_reset_tokens';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';


    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = false;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = PasswordResetTokenLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = PasswordResetTokenLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'email',
        'token',
        'created_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'created_at' => 'datetime',
        ];
    }

}
