<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\RefreshTokenLocales;

/**
 * RefreshTokenBaseModel
 *
 * @property string $token_hash
 * @property mixed $expires_at
 * @property mixed|null $revoked_at
 * @property string|null $ip_address
 * @property string|null $user_agent
 * @property mixed $created_at
 * @property int $user_id
 */
class RefreshTokenBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    /**
     * The table associated with the model.
     */
    protected $table = 'refresh_tokens';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';


    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = false;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = RefreshTokenLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = RefreshTokenLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'token_hash',
        'expires_at',
        'revoked_at',
        'ip_address',
        'user_agent',
        'created_at',
        'user_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'expires_at' => 'datetime',
            'revoked_at' => 'datetime',
            'created_at' => 'datetime',
        ];
    }

    /**
     * Get the user that owns this model.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(\Omnify\Core\Models\User::class, 'user_id');
    }
}
