<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\RolePermissionLocales;

/**
 * RolePermissionBaseModel
 *
 * @property int $role_id
 * @property int $permission_id
 */
class RolePermissionBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    /**
     * The table associated with the model.
     */
    protected $table = 'role_permissions';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'role,permission';


    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = RolePermissionLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = RolePermissionLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'role_id',
        'permission_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
        ];
    }

    /**
     * Get the role that owns this model.
     */
    public function role(): BelongsTo
    {
        return $this->belongsTo(\Omnify\Core\Models\Role::class, 'role_id');
    }

    /**
     * Get the permission that owns this model.
     */
    public function permission(): BelongsTo
    {
        return $this->belongsTo(\Omnify\Core\Models\Permission::class, 'permission_id');
    }
}
