<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\RoleLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * RoleBaseModel
 *
 * @property string|null $console_organization_id
 * @property string $name
 * @property string $slug
 * @property string|null $description
 * @property int $level
 */
class RoleBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'roles';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = RoleLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = RoleLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'console_organization_id',
        'name',
        'slug',
        'description',
        'level',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'level' => 'integer',
        ];
    }

    /**
     * The permissions that belong to this model.
     */
    public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(\Omnify\Core\Models\Permission::class, 'role_permissions')
            ->withTimestamps();
    }
}
