<?php

namespace Omnify\Core\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\Core\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\Core\Models\Base\Locales\UserLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * UserBaseModel
 *
 * @property string $name
 * @property string $email
 * @property string|null $password
 * @property string|null $remember_token
 * @property mixed|null $email_verified_at
 * @property bool $is_default_password
 * @property bool $is_active
 * @property mixed|null $date_of_birth
 * @property string|null $phone
 * @property string|null $address
 * @property array|null $bank
 * @property string|null $avatar_url
 * @property string|null $bio
 * @property bool $is_standalone
 * @property string|null $console_user_id
 * @property string|null $console_organization_id
 * @property string|null $console_access_token
 * @property string|null $console_refresh_token
 * @property mixed|null $console_token_expires_at
 * @property string|null $google2fa_secret
 * @property string|null $two_factor_recovery_codes
 * @property mixed|null $two_factor_confirmed_at
 */
class UserBaseModel extends Authenticatable
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use Notifiable;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'users';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'remember_token',
        'email_verified_at',
        'is_default_password',
        'is_active',
        'date_of_birth',
        'phone',
        'address',
        'bank',
        'avatar_url',
        'bio',
        'is_standalone',
        'console_user_id',
        'console_organization_id',
        'console_access_token',
        'console_refresh_token',
        'console_token_expires_at',
        'google2fa_secret',
        'two_factor_recovery_codes',
        'two_factor_confirmed_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'password',
        'remember_token',
        'google2fa_secret',
        'two_factor_recovery_codes',
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'is_default_password' => 'boolean',
            'is_active' => 'boolean',
            'date_of_birth' => 'date',
            'bank' => 'array',
            'is_standalone' => 'boolean',
            'console_token_expires_at' => 'datetime',
            'two_factor_confirmed_at' => 'datetime',
        ];
    }

    /**
     * The roles that belong to this model.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(\Omnify\Core\Models\Role::class, 'role_user_pivot')
            ->withPivot('console_branch_id', 'console_organization_id')
            ->withTimestamps();
    }
}
