<?php

namespace Omnify\SsoClient\Models\Base;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Omnify\SsoClient\Models\Base\Traits\HasLocalizedDisplayName;
use Omnify\SsoClient\Models\Base\Locales\UserLocales;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * UserBaseModel
 *
 * @property string $name
 * @property string $email
 * @property string|null $password
 * @property string|null $remember_token
 * @property string|null $console_user_id
 * @property string|null $console_organization_id
 * @property string|null $console_access_token
 * @property string|null $console_refresh_token
 * @property mixed|null $console_token_expires_at
 */
class UserBaseModel extends Authenticatable
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use Notifiable;
    use SoftDeletes;
    /**
     * The table associated with the model.
     */
    protected $table = 'users';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'remember_token',
        'console_user_id',
        'console_organization_id',
        'console_access_token',
        'console_refresh_token',
        'console_token_expires_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'console_token_expires_at' => 'datetime',
        ];
    }

    /**
     * The roles that belong to this model.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(\Omnify\SsoClient\Models\Role::class, 'role_user')
            ->withPivot('console_branch_id', 'console_organization_id')
            ->withTimestamps();
    }
}
