<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Omnify\SsoClient\Models\Base\Locales\LocationLocales;

abstract class LocationUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'console_location_id' => ['sometimes', 'string', 'uuid', Rule::unique('locations')->ignore($this->route('location'))],
            'console_branch_id' => ['sometimes', 'string', 'uuid'],
            'console_organization_id' => ['sometimes', 'string', 'uuid'],
            'code' => ['sometimes', 'string', 'max:30'],
            'name' => ['sometimes', 'string', 'max:150'],
            'type' => ['sometimes', 'string', Rule::in(['office', 'warehouse', 'factory', 'store', 'clinic', 'restaurant', 'other'])],
            'is_active' => ['sometimes', 'boolean'],
            'address' => ['nullable', 'string'],
            'city' => ['nullable', 'string', 'max:100'],
            'state_province' => ['nullable', 'string', 'max:100'],
            'postal_code' => ['nullable', 'string', 'max:20'],
            'country_code' => ['nullable', 'string', 'max:2'],
            'latitude' => ['nullable', 'numeric'],
            'longitude' => ['nullable', 'numeric'],
            'phone' => ['nullable', 'string', 'max:20'],
            'email' => ['nullable', 'string', 'max:255', 'email'],
            'timezone' => ['nullable', 'string', 'max:50'],
            'capacity' => ['nullable', 'integer'],
            'sort_order' => ['sometimes', 'integer'],
            'description' => ['nullable', 'string'],
            'settings' => ['nullable', 'array'],
            'metadata' => ['nullable', 'array'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = LocationLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'console_location_id',
            'console_branch_id',
            'console_organization_id',
            'code',
            'name',
            'type',
            'is_active',
            'address',
            'city',
            'state_province',
            'postal_code',
            'country_code',
            'latitude',
            'longitude',
            'phone',
            'email',
            'timezone',
            'capacity',
            'sort_order',
            'description',
            'settings',
            'metadata',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
