<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Omnify\SsoClient\Models\Base\Locales\RefreshTokenLocales;

abstract class RefreshTokenStoreRequestBase extends FormRequest
{
    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'token_hash' => ['required', 'string', 'max:64'],
            'expires_at' => ['required', 'date'],
            'revoked_at' => ['nullable', 'date'],
            'ip_address' => ['nullable', 'string', 'max:45'],
            'user_agent' => ['nullable', 'string', 'max:500'],
            'created_at' => ['required', 'date'],
            'user_id' => ['required', 'integer', 'exists:users,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = RefreshTokenLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'token_hash',
            'expires_at',
            'revoked_at',
            'ip_address',
            'user_agent',
            'created_at',
            'user_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
