<?php

namespace App\Http\Requests\OmnifyBase;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Foundation\Http\FormRequest;
use Omnify\Core\Models\Base\Locales\UserLocales;

abstract class UserUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'name' => ['sometimes', 'string', 'max:255'],
            'email' => ['sometimes', 'string', 'max:255'],
            'password' => ['nullable', 'string', 'max:255'],
            'remember_token' => ['nullable', 'string', 'max:100'],
            'email_verified_at' => ['nullable', 'date'],
            'is_default_password' => ['sometimes', 'boolean'],
            'is_active' => ['sometimes', 'boolean'],
            'date_of_birth' => ['nullable', 'date'],
            'phone' => ['nullable', 'string', 'max:20'],
            'address' => ['nullable', 'string'],
            'bank' => ['nullable', 'array'],
            'avatar_url' => ['nullable', 'string', 'max:500'],
            'bio' => ['nullable', 'string'],
            'is_standalone' => ['sometimes', 'boolean'],
            'console_user_id' => ['nullable', 'string', 'uuid'],
            'console_organization_id' => ['nullable', 'string', 'uuid'],
            'console_access_token' => ['nullable', 'string'],
            'console_refresh_token' => ['nullable', 'string'],
            'console_token_expires_at' => ['nullable', 'date'],
            'google2fa_secret' => ['nullable', 'string', 'max:100'],
            'two_factor_recovery_codes' => ['nullable', 'string'],
            'two_factor_confirmed_at' => ['nullable', 'date'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = UserLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'name',
            'email',
            'password',
            'remember_token',
            'email_verified_at',
            'is_default_password',
            'is_active',
            'date_of_birth',
            'phone',
            'address',
            'bank',
            'avatar_url',
            'bio',
            'is_standalone',
            'console_user_id',
            'console_organization_id',
            'console_access_token',
            'console_refresh_token',
            'console_token_expires_at',
            'google2fa_secret',
            'two_factor_recovery_codes',
            'two_factor_confirmed_at',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
