<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Admin.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class AdminLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Admin',
        'ja' => '管理者',
        'vi' => 'Quản trị viên',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'en' => 'Name',
            'ja' => '名前',
            'vi' => 'Tên',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メールアドレス',
            'vi' => 'Email',
        ],
        'password' => [
            'en' => 'Password',
            'ja' => 'パスワード',
            'vi' => 'Mật khẩu',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'email_verified_at' => [
            'en' => 'Email Verified At',
            'ja' => 'メール認証日時',
            'vi' => 'Thời gian xác thực email',
        ],
        'remember_token' => [
            'en' => 'Remember Token',
            'ja' => 'Remember Token',
            'vi' => 'Remember Token',
        ],
    ];
}
