<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Branch.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class BranchLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Branch',
        'ja' => '支店',
        'vi' => 'Chi nhánh',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_branch_id' => [
            'en' => 'Console Branch ID',
            'ja' => 'Console Branch ID',
            'vi' => 'Console Branch ID',
        ],
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'code' => [
            'en' => 'Branch Code',
            'ja' => '支店コード',
            'vi' => 'Mã chi nhánh',
        ],
        'slug' => [
            'en' => 'Slug',
            'ja' => 'スラッグ',
            'vi' => 'Slug',
        ],
        'name' => [
            'en' => 'Branch Name',
            'ja' => '支店名',
            'vi' => 'Tên chi nhánh',
        ],
        'is_headquarters' => [
            'en' => 'Is Headquarters',
            'ja' => '本社',
            'vi' => 'Là trụ sở chính',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'console_brand_id' => [
            'en' => 'Console Brand ID',
            'ja' => 'Console Brand ID',
            'vi' => 'Console Brand ID',
        ],
        'is_standalone' => [
            'en' => 'Standalone',
            'ja' => 'スタンドアローン',
            'vi' => 'Standalone',
        ],
        'address' => [
            'en' => 'Address',
            'ja' => '住所',
            'vi' => 'Địa chỉ',
        ],
        'phone' => [
            'en' => 'Phone',
            'ja' => '電話番号',
            'vi' => 'Số điện thoại',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メール',
            'vi' => 'Email',
        ],
        'timezone' => [
            'en' => 'Timezone',
            'ja' => 'タイムゾーン',
            'vi' => 'Múi giờ',
        ],
        'currency' => [
            'en' => 'Currency',
            'ja' => '通貨',
            'vi' => 'Tiền tệ',
        ],
        'locale' => [
            'en' => 'Locale',
            'ja' => 'ロケール',
            'vi' => 'Ngôn ngữ',
        ],
        'settings' => [
            'en' => 'Settings',
            'ja' => '設定',
            'vi' => 'Cài đặt',
        ],
        'metadata' => [
            'en' => 'Metadata',
            'ja' => 'メタデータ',
            'vi' => 'Metadata',
        ],
    ];
}
