<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Brand.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class BrandLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Brand',
        'ja' => 'ブランド',
        'vi' => 'Thương hiệu',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_brand_id' => [
            'en' => 'Console Brand ID',
            'ja' => 'Console Brand ID',
            'vi' => 'Console Brand ID',
        ],
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'slug' => [
            'en' => 'Slug',
            'ja' => 'スラッグ',
            'vi' => 'Slug',
        ],
        'name' => [
            'en' => 'Brand Name',
            'ja' => 'ブランド名',
            'vi' => 'Tên thương hiệu',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'logo_url' => [
            'en' => 'Logo URL',
            'ja' => 'ロゴURL',
            'vi' => 'URL logo',
        ],
        'cover_image_url' => [
            'en' => 'Cover Image URL',
            'ja' => 'カバー画像URL',
            'vi' => 'URL ảnh bìa',
        ],
        'website' => [
            'en' => 'Website',
            'ja' => 'ウェブサイト',
            'vi' => 'Website',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'is_standalone' => [
            'en' => 'Standalone',
            'ja' => 'スタンドアローン',
            'vi' => 'Standalone',
        ],
        'settings' => [
            'en' => 'Settings',
            'ja' => '設定',
            'vi' => 'Cài đặt',
        ],
        'metadata' => [
            'en' => 'Metadata',
            'ja' => 'メタデータ',
            'vi' => 'Metadata',
        ],
    ];
}
