<?php

namespace Omnify\SsoClient\Models\Base\Locales;

/**
 * Localized display names for Branch.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class BranchLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Branch',
        'ja' => '支店',
        'vi' => 'Chi nhánh',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_branch_id' => [
            'en' => 'Console Branch ID',
            'ja' => 'Console Branch ID',
            'vi' => 'Console Branch ID',
        ],
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'slug' => [
            'en' => 'Slug',
            'ja' => 'スラッグ',
            'vi' => 'Slug',
        ],
        'name' => [
            'en' => 'Branch Name',
            'ja' => '支店名',
            'vi' => 'Tên chi nhánh',
        ],
        'is_headquarters' => [
            'en' => 'Is Headquarters',
            'ja' => '本社',
            'vi' => 'Là trụ sở chính',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
    ];
}
