<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Location.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class LocationLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Location',
        'ja' => '拠点',
        'vi' => 'Địa điểm',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_location_id' => [
            'en' => 'Console Location ID',
            'ja' => 'Console Location ID',
            'vi' => 'Console Location ID',
        ],
        'console_branch_id' => [
            'en' => 'Console Branch ID',
            'ja' => 'Console Branch ID',
            'vi' => 'Console Branch ID',
        ],
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'code' => [
            'en' => 'Location Code',
            'ja' => '拠点コード',
            'vi' => 'Mã địa điểm',
        ],
        'name' => [
            'en' => 'Location Name',
            'ja' => '拠点名',
            'vi' => 'Tên địa điểm',
        ],
        'type' => [
            'en' => 'Location Type',
            'ja' => '拠点タイプ',
            'vi' => 'Loại địa điểm',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'is_standalone' => [
            'en' => 'Standalone',
            'ja' => 'スタンドアローン',
            'vi' => 'Standalone',
        ],
        'address' => [
            'en' => 'Address',
            'ja' => '住所',
            'vi' => 'Địa chỉ',
        ],
        'city' => [
            'en' => 'City',
            'ja' => '市区町村',
            'vi' => 'Thành phố',
        ],
        'state_province' => [
            'en' => 'State/Province',
            'ja' => '都道府県',
            'vi' => 'Tỉnh/Thành phố',
        ],
        'postal_code' => [
            'en' => 'Postal Code',
            'ja' => '郵便番号',
            'vi' => 'Mã bưu chính',
        ],
        'country_code' => [
            'en' => 'Country Code',
            'ja' => '国コード',
            'vi' => 'Mã quốc gia',
        ],
        'latitude' => [
            'en' => 'Latitude',
            'ja' => '緯度',
            'vi' => 'Vĩ độ',
        ],
        'longitude' => [
            'en' => 'Longitude',
            'ja' => '経度',
            'vi' => 'Kinh độ',
        ],
        'phone' => [
            'en' => 'Phone',
            'ja' => '電話番号',
            'vi' => 'Số điện thoại',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メール',
            'vi' => 'Email',
        ],
        'timezone' => [
            'en' => 'Timezone',
            'ja' => 'タイムゾーン',
            'vi' => 'Múi giờ',
        ],
        'capacity' => [
            'en' => 'Capacity',
            'ja' => '収容人数',
            'vi' => 'Sức chứa',
        ],
        'sort_order' => [
            'en' => 'Sort Order',
            'ja' => '並び順',
            'vi' => 'Thứ tự sắp xếp',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'settings' => [
            'en' => 'Settings',
            'ja' => '設定',
            'vi' => 'Cài đặt',
        ],
        'metadata' => [
            'en' => 'Metadata',
            'ja' => 'メタデータ',
            'vi' => 'Metadata',
        ],
    ];
}
