<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Organization.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class OrganizationLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Organization',
        'ja' => '組織',
        'vi' => 'Tổ chức',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'name' => [
            'en' => 'Organization Name',
            'ja' => '組織名',
            'vi' => 'Tên tổ chức',
        ],
        'slug' => [
            'en' => 'Slug',
            'ja' => 'スラッグ',
            'vi' => 'Slug',
        ],
        'is_standalone' => [
            'en' => 'Standalone',
            'ja' => 'スタンドアローン',
            'vi' => 'Standalone',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'settings' => [
            'en' => 'Settings',
            'ja' => '設定',
            'vi' => 'Cài đặt',
        ],
        'allowed_ips' => [
            'en' => 'Allowed IPs',
            'ja' => '許可IPアドレス',
            'vi' => 'IP được phép',
        ],
        'suspended_at' => [
            'en' => 'Suspended At',
            'ja' => '停止日時',
            'vi' => 'Thời gian tạm ngừng',
        ],
        'terminated_at' => [
            'en' => 'Terminated At',
            'ja' => '終了日時',
            'vi' => 'Thời gian chấm dứt',
        ],
    ];
}
