<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for PasswordResetToken.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class PasswordResetTokenLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Password Reset Token',
        'ja' => 'パスワードリセットトークン',
        'vi' => 'Token đặt lại mật khẩu',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'email' => [
            'en' => 'Email',
            'ja' => 'メールアドレス',
            'vi' => 'Email',
        ],
        'token' => [
            'en' => 'Token',
            'ja' => 'トークン',
            'vi' => 'Token',
        ],
        'created_at' => [
            'en' => 'Created At',
            'ja' => '作成日時',
            'vi' => 'Ngày tạo',
        ],
    ];
}
