<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for RefreshToken.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class RefreshTokenLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Refresh Token',
        'ja' => 'リフレッシュトークン',
        'vi' => 'Refresh Token',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'token_hash' => [
            'en' => 'Token Hash',
            'ja' => 'トークンハッシュ',
            'vi' => 'Hash token',
        ],
        'expires_at' => [
            'en' => 'Expires At',
            'ja' => '有効期限',
            'vi' => 'Hết hạn lúc',
        ],
        'revoked_at' => [
            'en' => 'Revoked At',
            'ja' => '取消日時',
            'vi' => 'Thu hồi lúc',
        ],
        'ip_address' => [
            'en' => 'IP Address',
            'ja' => 'IPアドレス',
            'vi' => 'Địa chỉ IP',
        ],
        'user_agent' => [
            'en' => 'User Agent',
            'ja' => 'ユーザーエージェント',
            'vi' => 'User Agent',
        ],
        'created_at' => [
            'en' => 'Created At',
            'ja' => '作成日時',
            'vi' => 'Tạo lúc',
        ],
    ];
}
