<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for RolePermission.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class RolePermissionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Role Permission',
        'ja' => 'ロール権限',
        'vi' => 'Quyền vai trò',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [];
}
