<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for Role.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class RoleLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Role',
        'ja' => 'ロール',
        'vi' => 'Vai trò',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_organization_id' => [
            'en' => 'Organization ID',
            'ja' => '組織ID',
            'vi' => 'ID tổ chức',
        ],
        'name' => [
            'en' => 'Role Name',
            'ja' => 'ロール名',
            'vi' => 'Tên vai trò',
        ],
        'slug' => [
            'en' => 'Slug',
            'ja' => 'スラッグ',
            'vi' => 'Slug',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'level' => [
            'en' => 'Level',
            'ja' => 'レベル',
            'vi' => 'Cấp độ',
        ],
    ];
}
