<?php

namespace Omnify\SsoClient\Models\Base\Locales;

/**
 * Localized display names for TeamPermission.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class TeamPermissionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Team Permission',
        'ja' => 'チーム権限',
        'vi' => 'Quyền nhóm',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'console_organization_id' => [
            'en' => 'Console Organization ID',
            'ja' => 'Console Organization ID',
            'vi' => 'Console Organization ID',
        ],
        'console_team_id' => [
            'en' => 'Console Team ID',
            'ja' => 'Console Team ID',
            'vi' => 'Console Team ID',
        ],
    ];
}
