<?php

namespace Omnify\SsoClient\Models\Base\Locales;

/**
 * Localized display names for User.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class UserLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'User',
        'ja' => 'ユーザー',
        'vi' => 'Người dùng',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'en' => 'Name',
            'ja' => '名前',
            'vi' => 'Tên',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メールアドレス',
            'vi' => 'Email',
        ],
        'password' => [
            'en' => 'Password',
            'ja' => 'パスワード',
            'vi' => 'Mật khẩu',
        ],
        'remember_token' => [
            'en' => 'Remember Token',
            'ja' => 'Remember Token',
            'vi' => 'Remember Token',
        ],
        'console_user_id' => [
            'en' => 'Console User ID',
            'ja' => 'Console User ID',
            'vi' => 'Console User ID',
        ],
        'console_organization_id' => [
            'en' => 'Organization ID',
            'ja' => '所属組織ID',
            'vi' => 'ID Tổ chức',
        ],
        'console_access_token' => [
            'en' => 'Console Access Token',
            'ja' => 'Console Access Token',
            'vi' => 'Console Access Token',
        ],
        'console_refresh_token' => [
            'en' => 'Console Refresh Token',
            'ja' => 'Console Refresh Token',
            'vi' => 'Console Refresh Token',
        ],
        'console_token_expires_at' => [
            'en' => 'Console Token Expiry',
            'ja' => 'Console Token有効期限',
            'vi' => 'Hạn Token Console',
        ],
    ];
}
