<?php

namespace Omnify\Core\Models\Base\Locales;

/**
 * Localized display names for User.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class UserLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'User',
        'ja' => 'ユーザー',
        'vi' => 'Người dùng',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'en' => 'Name',
            'ja' => '名前',
            'vi' => 'Tên',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メールアドレス',
            'vi' => 'Email',
        ],
        'password' => [
            'en' => 'Password',
            'ja' => 'パスワード',
            'vi' => 'Mật khẩu',
        ],
        'remember_token' => [
            'en' => 'Remember Token',
            'ja' => 'Remember Token',
            'vi' => 'Remember Token',
        ],
        'email_verified_at' => [
            'en' => 'Email Verified At',
            'ja' => 'メール認証日時',
            'vi' => 'Thời gian xác minh email',
        ],
        'is_default_password' => [
            'en' => 'Is Default Password',
            'ja' => 'デフォルトパスワード',
            'vi' => 'Mật khẩu mặc định',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'date_of_birth' => [
            'en' => 'Date of Birth',
            'ja' => '生年月日',
            'vi' => 'Ngày sinh',
        ],
        'phone' => [
            'en' => 'Phone Number',
            'ja' => '電話番号',
            'vi' => 'Số điện thoại',
        ],
        'address' => [
            'en' => 'Address',
            'ja' => '住所',
            'vi' => 'Địa chỉ',
        ],
        'bank' => [
            'en' => 'Bank Account',
            'ja' => '銀行口座',
            'vi' => 'Tài khoản ngân hàng',
        ],
        'avatar_url' => [
            'en' => 'Avatar URL',
            'ja' => 'アバターURL',
            'vi' => 'URL ảnh đại diện',
        ],
        'bio' => [
            'en' => 'Bio',
            'ja' => '自己紹介',
            'vi' => 'Giới thiệu bản thân',
        ],
        'is_standalone' => [
            'en' => 'Standalone',
            'ja' => 'スタンドアローン',
            'vi' => 'Standalone',
        ],
        'console_user_id' => [
            'en' => 'Console User ID',
            'ja' => 'Console User ID',
            'vi' => 'Console User ID',
        ],
        'console_organization_id' => [
            'en' => 'Organization ID',
            'ja' => '所属組織ID',
            'vi' => 'ID Tổ chức',
        ],
        'console_access_token' => [
            'en' => 'Console Access Token',
            'ja' => 'Console Access Token',
            'vi' => 'Console Access Token',
        ],
        'console_refresh_token' => [
            'en' => 'Console Refresh Token',
            'ja' => 'Console Refresh Token',
            'vi' => 'Console Refresh Token',
        ],
        'console_token_expires_at' => [
            'en' => 'Console Token Expiry',
            'ja' => 'Console Token有効期限',
            'vi' => 'Hạn Token Console',
        ],
        'google2fa_secret' => [
            'en' => '2FA Secret',
            'ja' => '2FAシークレット',
            'vi' => '2FA Secret',
        ],
        'two_factor_recovery_codes' => [
            'en' => '2FA Recovery Codes',
            'ja' => '2FAリカバリーコード',
            'vi' => 'Ma khoi phuc 2FA',
        ],
        'two_factor_confirmed_at' => [
            'en' => '2FA Confirmed At',
            'ja' => '2FA確認日時',
            'vi' => 'Thoi gian xac nhan 2FA',
        ],
    ];
}
