<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('locations', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('console_location_id')->unique()->comment('Console Location ID');
            $table->uuid('console_branch_id')->comment('Console Branch ID');
            $table->uuid('console_organization_id')->comment('Console Organization ID');
            $table->string('code', 30)->comment('Location Code');
            $table->string('name', 150)->comment('Location Name');
            $table->enum('type', ['office', 'warehouse', 'factory', 'store', 'clinic', 'restaurant', 'other'])->default('office')->comment('Location Type');
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->text('address')->nullable()->comment('Address');
            $table->string('city', 100)->nullable()->comment('City');
            $table->string('state_province', 100)->nullable()->comment('State/Province');
            $table->string('postal_code', 20)->nullable()->comment('Postal Code');
            $table->string('country_code', 2)->nullable()->comment('Country Code');
            $table->decimal('latitude', 10, 7)->nullable()->comment('Latitude');
            $table->decimal('longitude', 10, 7)->nullable()->comment('Longitude');
            $table->string('phone', 20)->nullable()->comment('Phone');
            $table->string('email')->nullable()->comment('Email');
            $table->string('timezone', 50)->nullable()->comment('Timezone');
            $table->integer('capacity')->nullable()->comment('Capacity');
            $table->integer('sort_order')->default(0)->comment('Sort Order');
            $table->text('description')->nullable()->comment('Description');
            $table->json('settings')->nullable()->comment('Settings');
            $table->json('metadata')->nullable()->comment('Metadata');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->unique(['console_branch_id', 'code']);
            $table->index(['console_organization_id', 'is_active']);
            $table->index(['console_branch_id', 'is_active']);
            $table->index(['console_organization_id', 'type']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('locations');
    }
};
