<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->date('date_of_birth')->nullable()->comment('Date of Birth');
            $table->text('bio')->nullable()->comment('Bio');
            $table->timestamp('email_verified_at')->nullable()->comment('Email Verified At');
            $table->string('phone', 20)->nullable()->comment('Phone Number');
            $table->text('address')->nullable()->comment('Address');
            $table->json('bank')->nullable()->comment('Bank Account');
            $table->boolean('is_default_password')->default(false)->comment('Is Default Password');
            $table->string('avatar_url', 500)->nullable()->comment('Avatar URL');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('is_active');
            $table->dropColumn('date_of_birth');
            $table->dropColumn('bio');
            $table->dropColumn('email_verified_at');
            $table->dropColumn('phone');
            $table->dropColumn('address');
            $table->dropColumn('bank');
            $table->dropColumn('is_default_password');
            $table->dropColumn('avatar_url');
        });
    }
};
