<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('refresh_tokens', function (Blueprint $table) {
            $table->id();
            $table->string('token_hash', 64)->comment('Token Hash');
            $table->timestamp('expires_at')->comment('Expires At');
            $table->timestamp('revoked_at')->nullable()->comment('Revoked At');
            $table->string('ip_address', 45)->nullable()->comment('IP Address');
            $table->string('user_agent', 500)->nullable()->comment('User Agent');
            $table->timestamp('created_at')->useCurrent()->comment('Created At');
            $table->uuid('user_id')->comment('User');
            $table->foreign('user_id')->references('id')->on('users')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('user_id');
            $table->index('token_hash');
            $table->index('expires_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('refresh_tokens');
    }
};
