<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('name')->comment('Name');
            $table->string('email')->comment('Email');
            $table->string('password')->nullable()->comment('Password');
            $table->string('remember_token', 100)->nullable()->comment('Remember Token');
            $table->boolean('is_standalone')->default(false)->comment('Standalone');
            $table->uuid('console_user_id')->nullable()->comment('Console User ID');
            $table->uuid('console_organization_id')->nullable()->comment('Organization ID');
            $table->text('console_access_token')->nullable()->comment('Console Access Token');
            $table->text('console_refresh_token')->nullable()->comment('Console Refresh Token');
            $table->timestamp('console_token_expires_at')->nullable()->comment('Console Token Expiry');
            $table->string('google2fa_secret', 100)->nullable()->comment('2FA Secret');
            $table->text('two_factor_recovery_codes')->nullable()->comment('2FA Recovery Codes');
            $table->timestamp('two_factor_confirmed_at')->nullable()->comment('2FA Confirmed At');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->index('console_organization_id');
            $table->unique(['email', 'console_organization_id']);
            $table->unique(['console_user_id', 'console_organization_id']);
            $table->index('is_standalone');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
