<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('branches', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('console_branch_id')->unique()->comment('Console Branch ID');
            $table->uuid('console_organization_id')->comment('Console Organization ID');
            $table->string('code', 20)->nullable()->comment('Branch Code');
            $table->string('slug', 100)->comment('Slug');
            $table->string('name', 100)->comment('Branch Name');
            $table->boolean('is_headquarters')->default(false)->comment('Is Headquarters');
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->uuid('console_brand_id')->nullable()->comment('Console Brand ID');
            $table->boolean('is_standalone')->default(false)->comment('Standalone');
            $table->text('address')->nullable()->comment('Address');
            $table->string('phone', 20)->nullable()->comment('Phone');
            $table->string('email')->nullable()->comment('Email');
            $table->string('timezone', 50)->nullable()->comment('Timezone');
            $table->string('currency', 3)->nullable()->comment('Currency');
            $table->string('locale', 10)->nullable()->comment('Locale');
            $table->json('settings')->nullable()->comment('Settings');
            $table->json('metadata')->nullable()->comment('Metadata');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->index('console_organization_id');
            $table->unique(['console_organization_id', 'slug']);
            $table->index(['console_organization_id', 'is_active']);
            $table->index(['console_organization_id', 'is_headquarters']);
            $table->index('console_brand_id');
            $table->index('is_standalone');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('branches');
    }
};
