<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('organizations', function (Blueprint $table) {
            $table->json('settings')->nullable()->comment('Settings');
            $table->json('allowed_ips')->nullable()->comment('Allowed IPs');
            $table->timestamp('suspended_at')->nullable()->comment('Suspended At');
            $table->timestamp('terminated_at')->nullable()->comment('Terminated At');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('organizations', function (Blueprint $table) {
            $table->dropColumn('settings');
            $table->dropColumn('allowed_ips');
            $table->dropColumn('suspended_at');
            $table->dropColumn('terminated_at');
        });
    }
};
