<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('branches', function (Blueprint $table) {
            $table->string('currency', 3)->nullable()->comment('Currency');
            $table->json('metadata')->nullable()->comment('Metadata');
            $table->string('phone', 20)->nullable()->comment('Phone');
            $table->json('settings')->nullable()->comment('Settings');
            $table->text('address')->nullable()->comment('Address');
            $table->string('code', 20)->nullable()->comment('Branch Code');
            $table->string('email')->nullable()->comment('Email');
            $table->string('locale', 10)->nullable()->comment('Locale');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('branches', function (Blueprint $table) {
            $table->dropColumn('currency');
            $table->dropColumn('metadata');
            $table->dropColumn('phone');
            $table->dropColumn('settings');
            $table->dropColumn('address');
            $table->dropColumn('code');
            $table->dropColumn('email');
            $table->dropColumn('locale');
        });
    }
};
