<?php

namespace Omnify\Core\Providers;

use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\ServiceProvider;

/**
 * Omnify Service Provider
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * - Loads Omnify migrations from database/migrations/omnify
 * - Registers morph map for polymorphic relationships
 *
 * @generated by omnify
 */
class OmnifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // Load Omnify migrations from custom directory
        $this->loadMigrationsFrom(database_path('migrations/omnify'));

        // Register morph map for polymorphic relationships
        Relation::enforceMorphMap([
            'Admin' => \Omnify\Core\Models\Admin::class,
            'Branch' => \Omnify\Core\Models\Branch::class,
            'Brand' => \Omnify\Core\Models\Brand::class,
            'Location' => \Omnify\Core\Models\Location::class,
            'Organization' => \Omnify\Core\Models\Organization::class,
            'Permission' => \Omnify\Core\Models\Permission::class,
            'RefreshToken' => \Omnify\Core\Models\RefreshToken::class,
            'Role' => \Omnify\Core\Models\Role::class,
            'RolePermission' => \Omnify\Core\Models\RolePermission::class,
            'Team' => \Omnify\Core\Models\Team::class,
            'TeamPermission' => \Omnify\Core\Models\TeamPermission::class,
            'User' => \Omnify\Core\Models\User::class,
        ]);
    }
}
